spring.application.name=RailTrackBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/railtrack
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD

jwt.secret=YOUR_SECRET_KEY
jwt.expiration=86400000

rapidapi.key=YOUR_RAPIDAPI_KEY
rapidapi.host=YOUR_HOST
rapidapi.base-url=YOUR_BASE_URL

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL_ADDRESS
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true